# Generated by Django 5.2.14 on 2026-05-26 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsagePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='digitalocean', max_length=32)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('source', models.CharField(default='utc_calendar_month', max_length=64)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='PeerUsageRuntimeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_rx_bytes', models.BigIntegerField(default=0)),
                ('last_tx_bytes', models.BigIntegerField(default=0)),
                ('last_sampled_at', models.DateTimeField(blank=True, null=True)),
                ('peer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='peers.peer')),
            ],
        ),
        migrations.CreateModel(
            name='DropletUsagePeriodTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_inbound_bytes', models.BigIntegerField(default=0)),
                ('public_outbound_bytes', models.BigIntegerField(default=0)),
                ('private_inbound_bytes', models.BigIntegerField(default=0)),
                ('private_outbound_bytes', models.BigIntegerField(default=0)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usage.usageperiod')),
            ],
        ),
        migrations.CreateModel(
            name='PeerUsagePeriodTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rx_bytes', models.BigIntegerField(default=0)),
                ('tx_bytes', models.BigIntegerField(default=0)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peers.peer')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usage.usageperiod')),
            ],
            options={
                'unique_together': {('period', 'peer')},
            },
        ),
    ]
